#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbQuanLyCafe")]
	public partial class dbcsdlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbLoaiSanPham(tbLoaiSanPham instance);
    partial void UpdatetbLoaiSanPham(tbLoaiSanPham instance);
    partial void DeletetbLoaiSanPham(tbLoaiSanPham instance);
    partial void InserttbThanhPham(tbThanhPham instance);
    partial void UpdatetbThanhPham(tbThanhPham instance);
    partial void DeletetbThanhPham(tbThanhPham instance);
    partial void InserttbKhuVuc(tbKhuVuc instance);
    partial void UpdatetbKhuVuc(tbKhuVuc instance);
    partial void DeletetbKhuVuc(tbKhuVuc instance);
    partial void InserttbBan(tbBan instance);
    partial void UpdatetbBan(tbBan instance);
    partial void DeletetbBan(tbBan instance);
    partial void InserttbHoaDonChiTiet(tbHoaDonChiTiet instance);
    partial void UpdatetbHoaDonChiTiet(tbHoaDonChiTiet instance);
    partial void DeletetbHoaDonChiTiet(tbHoaDonChiTiet instance);
    partial void InserttbTaiKhoan(tbTaiKhoan instance);
    partial void UpdatetbTaiKhoan(tbTaiKhoan instance);
    partial void DeletetbTaiKhoan(tbTaiKhoan instance);
    partial void InserttbHoaDon(tbHoaDon instance);
    partial void UpdatetbHoaDon(tbHoaDon instance);
    partial void DeletetbHoaDon(tbHoaDon instance);
    partial void InserttbNguyenLieu(tbNguyenLieu instance);
    partial void UpdatetbNguyenLieu(tbNguyenLieu instance);
    partial void DeletetbNguyenLieu(tbNguyenLieu instance);
    partial void InserttbNhapHang(tbNhapHang instance);
    partial void UpdatetbNhapHang(tbNhapHang instance);
    partial void DeletetbNhapHang(tbNhapHang instance);
    partial void InserttbNhapHangChiTiet(tbNhapHangChiTiet instance);
    partial void UpdatetbNhapHangChiTiet(tbNhapHangChiTiet instance);
    partial void DeletetbNhapHangChiTiet(tbNhapHangChiTiet instance);
    #endregion
		
		public dbcsdlDataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.dbQuanLyCafeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbcsdlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbLoaiSanPham> tbLoaiSanPhams
		{
			get
			{
				return this.GetTable<tbLoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tbThanhPham> tbThanhPhams
		{
			get
			{
				return this.GetTable<tbThanhPham>();
			}
		}
		
		public System.Data.Linq.Table<tbKhuVuc> tbKhuVucs
		{
			get
			{
				return this.GetTable<tbKhuVuc>();
			}
		}
		
		public System.Data.Linq.Table<tbBan> tbBans
		{
			get
			{
				return this.GetTable<tbBan>();
			}
		}
		
		public System.Data.Linq.Table<tbHoaDonChiTiet> tbHoaDonChiTiets
		{
			get
			{
				return this.GetTable<tbHoaDonChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<tbTaiKhoan> tbTaiKhoans
		{
			get
			{
				return this.GetTable<tbTaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<tbHoaDon> tbHoaDons
		{
			get
			{
				return this.GetTable<tbHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tbNguyenLieu> tbNguyenLieus
		{
			get
			{
				return this.GetTable<tbNguyenLieu>();
			}
		}
		
		public System.Data.Linq.Table<tbNhapHang> tbNhapHangs
		{
			get
			{
				return this.GetTable<tbNhapHang>();
			}
		}
		
		public System.Data.Linq.Table<tbNhapHangChiTiet> tbNhapHangChiTiets
		{
			get
			{
				return this.GetTable<tbNhapHangChiTiet>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbLoaiSanPham")]
	public partial class tbLoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loaisanpham_id;
		
		private string _loaisanpham_ten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onloaisanpham_idChanging(int value);
    partial void Onloaisanpham_idChanged();
    partial void Onloaisanpham_tenChanging(string value);
    partial void Onloaisanpham_tenChanged();
    #endregion
		
		public tbLoaiSanPham()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int loaisanpham_id
		{
			get
			{
				return this._loaisanpham_id;
			}
			set
			{
				if ((this._loaisanpham_id != value))
				{
					this.Onloaisanpham_idChanging(value);
					this.SendPropertyChanging();
					this._loaisanpham_id = value;
					this.SendPropertyChanged("loaisanpham_id");
					this.Onloaisanpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_ten", DbType="NVarChar(MAX)")]
		public string loaisanpham_ten
		{
			get
			{
				return this._loaisanpham_ten;
			}
			set
			{
				if ((this._loaisanpham_ten != value))
				{
					this.Onloaisanpham_tenChanging(value);
					this.SendPropertyChanging();
					this._loaisanpham_ten = value;
					this.SendPropertyChanged("loaisanpham_ten");
					this.Onloaisanpham_tenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbThanhPham")]
	public partial class tbThanhPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _thanhpham_id;
		
		private string _thanhpham_ten;
		
		private System.Nullable<int> _thanhpham_soluong;
		
		private System.Nullable<decimal> _thanhpham_dongia;
		
		private System.Nullable<int> _loaisanpham_id;
		
		private string _loaisanpham_ten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onthanhpham_idChanging(int value);
    partial void Onthanhpham_idChanged();
    partial void Onthanhpham_tenChanging(string value);
    partial void Onthanhpham_tenChanged();
    partial void Onthanhpham_soluongChanging(System.Nullable<int> value);
    partial void Onthanhpham_soluongChanged();
    partial void Onthanhpham_dongiaChanging(System.Nullable<decimal> value);
    partial void Onthanhpham_dongiaChanged();
    partial void Onloaisanpham_idChanging(System.Nullable<int> value);
    partial void Onloaisanpham_idChanged();
    partial void Onloaisanpham_tenChanging(string value);
    partial void Onloaisanpham_tenChanged();
    #endregion
		
		public tbThanhPham()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhpham_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int thanhpham_id
		{
			get
			{
				return this._thanhpham_id;
			}
			set
			{
				if ((this._thanhpham_id != value))
				{
					this.Onthanhpham_idChanging(value);
					this.SendPropertyChanging();
					this._thanhpham_id = value;
					this.SendPropertyChanged("thanhpham_id");
					this.Onthanhpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhpham_ten", DbType="NVarChar(MAX)")]
		public string thanhpham_ten
		{
			get
			{
				return this._thanhpham_ten;
			}
			set
			{
				if ((this._thanhpham_ten != value))
				{
					this.Onthanhpham_tenChanging(value);
					this.SendPropertyChanging();
					this._thanhpham_ten = value;
					this.SendPropertyChanged("thanhpham_ten");
					this.Onthanhpham_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhpham_soluong", DbType="Int")]
		public System.Nullable<int> thanhpham_soluong
		{
			get
			{
				return this._thanhpham_soluong;
			}
			set
			{
				if ((this._thanhpham_soluong != value))
				{
					this.Onthanhpham_soluongChanging(value);
					this.SendPropertyChanging();
					this._thanhpham_soluong = value;
					this.SendPropertyChanged("thanhpham_soluong");
					this.Onthanhpham_soluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhpham_dongia", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> thanhpham_dongia
		{
			get
			{
				return this._thanhpham_dongia;
			}
			set
			{
				if ((this._thanhpham_dongia != value))
				{
					this.Onthanhpham_dongiaChanging(value);
					this.SendPropertyChanging();
					this._thanhpham_dongia = value;
					this.SendPropertyChanged("thanhpham_dongia");
					this.Onthanhpham_dongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_id", DbType="Int")]
		public System.Nullable<int> loaisanpham_id
		{
			get
			{
				return this._loaisanpham_id;
			}
			set
			{
				if ((this._loaisanpham_id != value))
				{
					this.Onloaisanpham_idChanging(value);
					this.SendPropertyChanging();
					this._loaisanpham_id = value;
					this.SendPropertyChanged("loaisanpham_id");
					this.Onloaisanpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaisanpham_ten", DbType="NVarChar(MAX)")]
		public string loaisanpham_ten
		{
			get
			{
				return this._loaisanpham_ten;
			}
			set
			{
				if ((this._loaisanpham_ten != value))
				{
					this.Onloaisanpham_tenChanging(value);
					this.SendPropertyChanging();
					this._loaisanpham_ten = value;
					this.SendPropertyChanged("loaisanpham_ten");
					this.Onloaisanpham_tenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbKhuVuc")]
	public partial class tbKhuVuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _khuvuc_id;
		
		private string _khuvuc_ten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkhuvuc_idChanging(int value);
    partial void Onkhuvuc_idChanged();
    partial void Onkhuvuc_tenChanging(string value);
    partial void Onkhuvuc_tenChanged();
    #endregion
		
		public tbKhuVuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuvuc_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int khuvuc_id
		{
			get
			{
				return this._khuvuc_id;
			}
			set
			{
				if ((this._khuvuc_id != value))
				{
					this.Onkhuvuc_idChanging(value);
					this.SendPropertyChanging();
					this._khuvuc_id = value;
					this.SendPropertyChanged("khuvuc_id");
					this.Onkhuvuc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuvuc_ten", DbType="NVarChar(MAX)")]
		public string khuvuc_ten
		{
			get
			{
				return this._khuvuc_ten;
			}
			set
			{
				if ((this._khuvuc_ten != value))
				{
					this.Onkhuvuc_tenChanging(value);
					this.SendPropertyChanging();
					this._khuvuc_ten = value;
					this.SendPropertyChanged("khuvuc_ten");
					this.Onkhuvuc_tenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbBan")]
	public partial class tbBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ban_id;
		
		private string _ban_ten;
		
		private string _ban_trangthai;
		
		private System.Nullable<int> _khuvuc_id;
		
		private string _khuvuc_ten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onban_idChanging(int value);
    partial void Onban_idChanged();
    partial void Onban_tenChanging(string value);
    partial void Onban_tenChanged();
    partial void Onban_trangthaiChanging(string value);
    partial void Onban_trangthaiChanged();
    partial void Onkhuvuc_idChanging(System.Nullable<int> value);
    partial void Onkhuvuc_idChanged();
    partial void Onkhuvuc_tenChanging(string value);
    partial void Onkhuvuc_tenChanged();
    #endregion
		
		public tbBan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ban_id
		{
			get
			{
				return this._ban_id;
			}
			set
			{
				if ((this._ban_id != value))
				{
					this.Onban_idChanging(value);
					this.SendPropertyChanging();
					this._ban_id = value;
					this.SendPropertyChanged("ban_id");
					this.Onban_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_ten", DbType="NVarChar(MAX)")]
		public string ban_ten
		{
			get
			{
				return this._ban_ten;
			}
			set
			{
				if ((this._ban_ten != value))
				{
					this.Onban_tenChanging(value);
					this.SendPropertyChanging();
					this._ban_ten = value;
					this.SendPropertyChanged("ban_ten");
					this.Onban_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_trangthai", DbType="NVarChar(MAX)")]
		public string ban_trangthai
		{
			get
			{
				return this._ban_trangthai;
			}
			set
			{
				if ((this._ban_trangthai != value))
				{
					this.Onban_trangthaiChanging(value);
					this.SendPropertyChanging();
					this._ban_trangthai = value;
					this.SendPropertyChanged("ban_trangthai");
					this.Onban_trangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuvuc_id", DbType="Int")]
		public System.Nullable<int> khuvuc_id
		{
			get
			{
				return this._khuvuc_id;
			}
			set
			{
				if ((this._khuvuc_id != value))
				{
					this.Onkhuvuc_idChanging(value);
					this.SendPropertyChanging();
					this._khuvuc_id = value;
					this.SendPropertyChanged("khuvuc_id");
					this.Onkhuvuc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuvuc_ten", DbType="NVarChar(MAX)")]
		public string khuvuc_ten
		{
			get
			{
				return this._khuvuc_ten;
			}
			set
			{
				if ((this._khuvuc_ten != value))
				{
					this.Onkhuvuc_tenChanging(value);
					this.SendPropertyChanging();
					this._khuvuc_ten = value;
					this.SendPropertyChanged("khuvuc_ten");
					this.Onkhuvuc_tenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbHoaDonChiTiet")]
	public partial class tbHoaDonChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hoadonchitiet_id;
		
		private System.Nullable<int> _hoadon_id;
		
		private System.Nullable<int> _thanhpham_id;
		
		private System.Nullable<int> _thanhpham_soluong;
		
		private System.Nullable<int> _ban_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhoadonchitiet_idChanging(int value);
    partial void Onhoadonchitiet_idChanged();
    partial void Onhoadon_idChanging(System.Nullable<int> value);
    partial void Onhoadon_idChanged();
    partial void Onthanhpham_idChanging(System.Nullable<int> value);
    partial void Onthanhpham_idChanged();
    partial void Onthanhpham_soluongChanging(System.Nullable<int> value);
    partial void Onthanhpham_soluongChanged();
    partial void Onban_idChanging(System.Nullable<int> value);
    partial void Onban_idChanged();
    #endregion
		
		public tbHoaDonChiTiet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadonchitiet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hoadonchitiet_id
		{
			get
			{
				return this._hoadonchitiet_id;
			}
			set
			{
				if ((this._hoadonchitiet_id != value))
				{
					this.Onhoadonchitiet_idChanging(value);
					this.SendPropertyChanging();
					this._hoadonchitiet_id = value;
					this.SendPropertyChanged("hoadonchitiet_id");
					this.Onhoadonchitiet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_id", DbType="Int")]
		public System.Nullable<int> hoadon_id
		{
			get
			{
				return this._hoadon_id;
			}
			set
			{
				if ((this._hoadon_id != value))
				{
					this.Onhoadon_idChanging(value);
					this.SendPropertyChanging();
					this._hoadon_id = value;
					this.SendPropertyChanged("hoadon_id");
					this.Onhoadon_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhpham_id", DbType="Int")]
		public System.Nullable<int> thanhpham_id
		{
			get
			{
				return this._thanhpham_id;
			}
			set
			{
				if ((this._thanhpham_id != value))
				{
					this.Onthanhpham_idChanging(value);
					this.SendPropertyChanging();
					this._thanhpham_id = value;
					this.SendPropertyChanged("thanhpham_id");
					this.Onthanhpham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhpham_soluong", DbType="Int")]
		public System.Nullable<int> thanhpham_soluong
		{
			get
			{
				return this._thanhpham_soluong;
			}
			set
			{
				if ((this._thanhpham_soluong != value))
				{
					this.Onthanhpham_soluongChanging(value);
					this.SendPropertyChanging();
					this._thanhpham_soluong = value;
					this.SendPropertyChanged("thanhpham_soluong");
					this.Onthanhpham_soluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_id", DbType="Int")]
		public System.Nullable<int> ban_id
		{
			get
			{
				return this._ban_id;
			}
			set
			{
				if ((this._ban_id != value))
				{
					this.Onban_idChanging(value);
					this.SendPropertyChanging();
					this._ban_id = value;
					this.SendPropertyChanged("ban_id");
					this.Onban_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTaiKhoan")]
	public partial class tbTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _taikhoan_id;
		
		private string _taikhoan_hoten;
		
		private string _taikhoan_tentaikhoan;
		
		private string _taikhoan_matkhau;
		
		private string _taikhoan_hinhanh;
		
		private bool _taikhoan_quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontaikhoan_idChanging(int value);
    partial void Ontaikhoan_idChanged();
    partial void Ontaikhoan_hotenChanging(string value);
    partial void Ontaikhoan_hotenChanged();
    partial void Ontaikhoan_tentaikhoanChanging(string value);
    partial void Ontaikhoan_tentaikhoanChanged();
    partial void Ontaikhoan_matkhauChanging(string value);
    partial void Ontaikhoan_matkhauChanged();
    partial void Ontaikhoan_hinhanhChanging(string value);
    partial void Ontaikhoan_hinhanhChanged();
    partial void Ontaikhoan_quyenChanging(bool value);
    partial void Ontaikhoan_quyenChanged();
    #endregion
		
		public tbTaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int taikhoan_id
		{
			get
			{
				return this._taikhoan_id;
			}
			set
			{
				if ((this._taikhoan_id != value))
				{
					this.Ontaikhoan_idChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_id = value;
					this.SendPropertyChanged("taikhoan_id");
					this.Ontaikhoan_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_hoten", DbType="NVarChar(MAX)")]
		public string taikhoan_hoten
		{
			get
			{
				return this._taikhoan_hoten;
			}
			set
			{
				if ((this._taikhoan_hoten != value))
				{
					this.Ontaikhoan_hotenChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_hoten = value;
					this.SendPropertyChanged("taikhoan_hoten");
					this.Ontaikhoan_hotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_tentaikhoan", DbType="NVarChar(255)")]
		public string taikhoan_tentaikhoan
		{
			get
			{
				return this._taikhoan_tentaikhoan;
			}
			set
			{
				if ((this._taikhoan_tentaikhoan != value))
				{
					this.Ontaikhoan_tentaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_tentaikhoan = value;
					this.SendPropertyChanged("taikhoan_tentaikhoan");
					this.Ontaikhoan_tentaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_matkhau", DbType="NVarChar(MAX)")]
		public string taikhoan_matkhau
		{
			get
			{
				return this._taikhoan_matkhau;
			}
			set
			{
				if ((this._taikhoan_matkhau != value))
				{
					this.Ontaikhoan_matkhauChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_matkhau = value;
					this.SendPropertyChanged("taikhoan_matkhau");
					this.Ontaikhoan_matkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_hinhanh", DbType="NVarChar(MAX)")]
		public string taikhoan_hinhanh
		{
			get
			{
				return this._taikhoan_hinhanh;
			}
			set
			{
				if ((this._taikhoan_hinhanh != value))
				{
					this.Ontaikhoan_hinhanhChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_hinhanh = value;
					this.SendPropertyChanged("taikhoan_hinhanh");
					this.Ontaikhoan_hinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan_quyen", DbType="Bit NOT NULL")]
		public bool taikhoan_quyen
		{
			get
			{
				return this._taikhoan_quyen;
			}
			set
			{
				if ((this._taikhoan_quyen != value))
				{
					this.Ontaikhoan_quyenChanging(value);
					this.SendPropertyChanging();
					this._taikhoan_quyen = value;
					this.SendPropertyChanged("taikhoan_quyen");
					this.Ontaikhoan_quyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbHoaDon")]
	public partial class tbHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hoadon_id;
		
		private System.Nullable<System.DateTime> _hoadon_ngaynhap;
		
		private System.Nullable<System.DateTime> _hoadon_ngayxuat;
		
		private System.Nullable<int> _ban_id;
		
		private System.Nullable<int> _hoadon_trangthai;
		
		private string _hoadon_mahoadon;
		
		private System.Nullable<decimal> _hoadon_tongtien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhoadon_idChanging(int value);
    partial void Onhoadon_idChanged();
    partial void Onhoadon_ngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void Onhoadon_ngaynhapChanged();
    partial void Onhoadon_ngayxuatChanging(System.Nullable<System.DateTime> value);
    partial void Onhoadon_ngayxuatChanged();
    partial void Onban_idChanging(System.Nullable<int> value);
    partial void Onban_idChanged();
    partial void Onhoadon_trangthaiChanging(System.Nullable<int> value);
    partial void Onhoadon_trangthaiChanged();
    partial void Onhoadon_mahoadonChanging(string value);
    partial void Onhoadon_mahoadonChanged();
    partial void Onhoadon_tongtienChanging(System.Nullable<decimal> value);
    partial void Onhoadon_tongtienChanged();
    #endregion
		
		public tbHoaDon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hoadon_id
		{
			get
			{
				return this._hoadon_id;
			}
			set
			{
				if ((this._hoadon_id != value))
				{
					this.Onhoadon_idChanging(value);
					this.SendPropertyChanging();
					this._hoadon_id = value;
					this.SendPropertyChanged("hoadon_id");
					this.Onhoadon_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_ngaynhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> hoadon_ngaynhap
		{
			get
			{
				return this._hoadon_ngaynhap;
			}
			set
			{
				if ((this._hoadon_ngaynhap != value))
				{
					this.Onhoadon_ngaynhapChanging(value);
					this.SendPropertyChanging();
					this._hoadon_ngaynhap = value;
					this.SendPropertyChanged("hoadon_ngaynhap");
					this.Onhoadon_ngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_ngayxuat", DbType="DateTime")]
		public System.Nullable<System.DateTime> hoadon_ngayxuat
		{
			get
			{
				return this._hoadon_ngayxuat;
			}
			set
			{
				if ((this._hoadon_ngayxuat != value))
				{
					this.Onhoadon_ngayxuatChanging(value);
					this.SendPropertyChanging();
					this._hoadon_ngayxuat = value;
					this.SendPropertyChanged("hoadon_ngayxuat");
					this.Onhoadon_ngayxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ban_id", DbType="Int")]
		public System.Nullable<int> ban_id
		{
			get
			{
				return this._ban_id;
			}
			set
			{
				if ((this._ban_id != value))
				{
					this.Onban_idChanging(value);
					this.SendPropertyChanging();
					this._ban_id = value;
					this.SendPropertyChanged("ban_id");
					this.Onban_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_trangthai", DbType="Int")]
		public System.Nullable<int> hoadon_trangthai
		{
			get
			{
				return this._hoadon_trangthai;
			}
			set
			{
				if ((this._hoadon_trangthai != value))
				{
					this.Onhoadon_trangthaiChanging(value);
					this.SendPropertyChanging();
					this._hoadon_trangthai = value;
					this.SendPropertyChanged("hoadon_trangthai");
					this.Onhoadon_trangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_mahoadon", DbType="NVarChar(MAX)")]
		public string hoadon_mahoadon
		{
			get
			{
				return this._hoadon_mahoadon;
			}
			set
			{
				if ((this._hoadon_mahoadon != value))
				{
					this.Onhoadon_mahoadonChanging(value);
					this.SendPropertyChanging();
					this._hoadon_mahoadon = value;
					this.SendPropertyChanged("hoadon_mahoadon");
					this.Onhoadon_mahoadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoadon_tongtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> hoadon_tongtien
		{
			get
			{
				return this._hoadon_tongtien;
			}
			set
			{
				if ((this._hoadon_tongtien != value))
				{
					this.Onhoadon_tongtienChanging(value);
					this.SendPropertyChanging();
					this._hoadon_tongtien = value;
					this.SendPropertyChanged("hoadon_tongtien");
					this.Onhoadon_tongtienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbNguyenLieu")]
	public partial class tbNguyenLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nguyenlieu_id;
		
		private string _nguyenlieu_ten;
		
		private string _nguyenlieu_nhacungcap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnguyenlieu_idChanging(int value);
    partial void Onnguyenlieu_idChanged();
    partial void Onnguyenlieu_tenChanging(string value);
    partial void Onnguyenlieu_tenChanged();
    partial void Onnguyenlieu_nhacungcapChanging(string value);
    partial void Onnguyenlieu_nhacungcapChanged();
    #endregion
		
		public tbNguyenLieu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguyenlieu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nguyenlieu_id
		{
			get
			{
				return this._nguyenlieu_id;
			}
			set
			{
				if ((this._nguyenlieu_id != value))
				{
					this.Onnguyenlieu_idChanging(value);
					this.SendPropertyChanging();
					this._nguyenlieu_id = value;
					this.SendPropertyChanged("nguyenlieu_id");
					this.Onnguyenlieu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguyenlieu_ten", DbType="NVarChar(MAX)")]
		public string nguyenlieu_ten
		{
			get
			{
				return this._nguyenlieu_ten;
			}
			set
			{
				if ((this._nguyenlieu_ten != value))
				{
					this.Onnguyenlieu_tenChanging(value);
					this.SendPropertyChanging();
					this._nguyenlieu_ten = value;
					this.SendPropertyChanged("nguyenlieu_ten");
					this.Onnguyenlieu_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguyenlieu_nhacungcap", DbType="NVarChar(MAX)")]
		public string nguyenlieu_nhacungcap
		{
			get
			{
				return this._nguyenlieu_nhacungcap;
			}
			set
			{
				if ((this._nguyenlieu_nhacungcap != value))
				{
					this.Onnguyenlieu_nhacungcapChanging(value);
					this.SendPropertyChanging();
					this._nguyenlieu_nhacungcap = value;
					this.SendPropertyChanged("nguyenlieu_nhacungcap");
					this.Onnguyenlieu_nhacungcapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbNhapHang")]
	public partial class tbNhapHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nhaphang_id;
		
		private System.Nullable<System.DateTime> _nhaphang_ngaynhap;
		
		private System.Nullable<decimal> _nhaphang_tongtien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnhaphang_idChanging(string value);
    partial void Onnhaphang_idChanged();
    partial void Onnhaphang_ngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void Onnhaphang_ngaynhapChanged();
    partial void Onnhaphang_tongtienChanging(System.Nullable<decimal> value);
    partial void Onnhaphang_tongtienChanged();
    #endregion
		
		public tbNhapHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_id", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nhaphang_id
		{
			get
			{
				return this._nhaphang_id;
			}
			set
			{
				if ((this._nhaphang_id != value))
				{
					this.Onnhaphang_idChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_id = value;
					this.SendPropertyChanged("nhaphang_id");
					this.Onnhaphang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_ngaynhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> nhaphang_ngaynhap
		{
			get
			{
				return this._nhaphang_ngaynhap;
			}
			set
			{
				if ((this._nhaphang_ngaynhap != value))
				{
					this.Onnhaphang_ngaynhapChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_ngaynhap = value;
					this.SendPropertyChanged("nhaphang_ngaynhap");
					this.Onnhaphang_ngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_tongtien", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> nhaphang_tongtien
		{
			get
			{
				return this._nhaphang_tongtien;
			}
			set
			{
				if ((this._nhaphang_tongtien != value))
				{
					this.Onnhaphang_tongtienChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_tongtien = value;
					this.SendPropertyChanged("nhaphang_tongtien");
					this.Onnhaphang_tongtienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbNhapHangChiTiet")]
	public partial class tbNhapHangChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nhaphangchitiet_id;
		
		private string _nhaphangchitiet_sanpham;
		
		private string _nguyenlieu_nhacungcap;
		
		private System.Nullable<int> _nhaphangchitiet_soluong;
		
		private System.Nullable<int> _nhaphangchitiet_dongia;
		
		private System.Nullable<int> _nhaphangchitiet_thanhtien;
		
		private string _nhaphang_id;
		
		private System.Nullable<int> _nguyenlieu_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnhaphangchitiet_idChanging(int value);
    partial void Onnhaphangchitiet_idChanged();
    partial void Onnhaphangchitiet_sanphamChanging(string value);
    partial void Onnhaphangchitiet_sanphamChanged();
    partial void Onnguyenlieu_nhacungcapChanging(string value);
    partial void Onnguyenlieu_nhacungcapChanged();
    partial void Onnhaphangchitiet_soluongChanging(System.Nullable<int> value);
    partial void Onnhaphangchitiet_soluongChanged();
    partial void Onnhaphangchitiet_dongiaChanging(System.Nullable<int> value);
    partial void Onnhaphangchitiet_dongiaChanged();
    partial void Onnhaphangchitiet_thanhtienChanging(System.Nullable<int> value);
    partial void Onnhaphangchitiet_thanhtienChanged();
    partial void Onnhaphang_idChanging(string value);
    partial void Onnhaphang_idChanged();
    partial void Onnguyenlieu_idChanging(System.Nullable<int> value);
    partial void Onnguyenlieu_idChanged();
    #endregion
		
		public tbNhapHangChiTiet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nhaphangchitiet_id
		{
			get
			{
				return this._nhaphangchitiet_id;
			}
			set
			{
				if ((this._nhaphangchitiet_id != value))
				{
					this.Onnhaphangchitiet_idChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_id = value;
					this.SendPropertyChanged("nhaphangchitiet_id");
					this.Onnhaphangchitiet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_sanpham", DbType="NVarChar(MAX)")]
		public string nhaphangchitiet_sanpham
		{
			get
			{
				return this._nhaphangchitiet_sanpham;
			}
			set
			{
				if ((this._nhaphangchitiet_sanpham != value))
				{
					this.Onnhaphangchitiet_sanphamChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_sanpham = value;
					this.SendPropertyChanged("nhaphangchitiet_sanpham");
					this.Onnhaphangchitiet_sanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguyenlieu_nhacungcap", DbType="NVarChar(MAX)")]
		public string nguyenlieu_nhacungcap
		{
			get
			{
				return this._nguyenlieu_nhacungcap;
			}
			set
			{
				if ((this._nguyenlieu_nhacungcap != value))
				{
					this.Onnguyenlieu_nhacungcapChanging(value);
					this.SendPropertyChanging();
					this._nguyenlieu_nhacungcap = value;
					this.SendPropertyChanged("nguyenlieu_nhacungcap");
					this.Onnguyenlieu_nhacungcapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_soluong", DbType="Int")]
		public System.Nullable<int> nhaphangchitiet_soluong
		{
			get
			{
				return this._nhaphangchitiet_soluong;
			}
			set
			{
				if ((this._nhaphangchitiet_soluong != value))
				{
					this.Onnhaphangchitiet_soluongChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_soluong = value;
					this.SendPropertyChanged("nhaphangchitiet_soluong");
					this.Onnhaphangchitiet_soluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_dongia", DbType="Int")]
		public System.Nullable<int> nhaphangchitiet_dongia
		{
			get
			{
				return this._nhaphangchitiet_dongia;
			}
			set
			{
				if ((this._nhaphangchitiet_dongia != value))
				{
					this.Onnhaphangchitiet_dongiaChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_dongia = value;
					this.SendPropertyChanged("nhaphangchitiet_dongia");
					this.Onnhaphangchitiet_dongiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphangchitiet_thanhtien", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> nhaphangchitiet_thanhtien
		{
			get
			{
				return this._nhaphangchitiet_thanhtien;
			}
			set
			{
				if ((this._nhaphangchitiet_thanhtien != value))
				{
					this.Onnhaphangchitiet_thanhtienChanging(value);
					this.SendPropertyChanging();
					this._nhaphangchitiet_thanhtien = value;
					this.SendPropertyChanged("nhaphangchitiet_thanhtien");
					this.Onnhaphangchitiet_thanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaphang_id", DbType="NVarChar(255)")]
		public string nhaphang_id
		{
			get
			{
				return this._nhaphang_id;
			}
			set
			{
				if ((this._nhaphang_id != value))
				{
					this.Onnhaphang_idChanging(value);
					this.SendPropertyChanging();
					this._nhaphang_id = value;
					this.SendPropertyChanged("nhaphang_id");
					this.Onnhaphang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguyenlieu_id", DbType="Int")]
		public System.Nullable<int> nguyenlieu_id
		{
			get
			{
				return this._nguyenlieu_id;
			}
			set
			{
				if ((this._nguyenlieu_id != value))
				{
					this.Onnguyenlieu_idChanging(value);
					this.SendPropertyChanging();
					this._nguyenlieu_id = value;
					this.SendPropertyChanged("nguyenlieu_id");
					this.Onnguyenlieu_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
